### ISSUE TITLE
epc_exempt_uri_contains runs before theme

### ISSUE THREAD

**Issue by vdwijngaert** [bluehost/endurance-page-cache#1]
Great start!

I couldn't help but notice this line of code:

`$this->cache_exempt = apply_filters( 'epc_exempt_uri_contains', array( 'wp-admin', '.php', 'checkout', 'cart' ) );
`

This implies that you can alter the array of cache exceptions. I could be wrong, but doesn't this line of code run before the theme initializes? I think plugins that are being loaded after EPC don't get a chance to hook into that filter as well.

**Comment by MikeHansenMe** [comment]
You are correct. You would have to include another mu-plugin to get in there before that runs. I could update it to be an option with that array as the default. Then a theme/plugin could modify that option and get in there before the theme/plugin even loads. 

Thanks for catching this and opening an issue.

**Comment by vdwijngaert** [comment]
Happy to help! :)

**Comment by MikeHansenMe** [comment]
I think I found a better solution that an option by just moving the filter where it can be hooked (on init before 10). 

https://github.com/bluehost/endurance-page-cache/commit/a6203b7efa6c1671bac9b2af11ca2a895f0d3fe2
