### ISSUE TITLE
Homepage is always loading cached version only

### ISSUE THREAD

**Issue by BlindDespair** [bluehost/endurance-page-cache#15]
Hello. My client has a website on Blue Host and he hired me to solve the issue where the main page on the website doesn't update after changes in wordpress. I tried clearing all kinds of caches, disabled it, changed .htaccess file, nothing helped. Then I went to file manager, deleted everything from endurance-page-cache
folder, it also didn't help. I just can't find where this cached version of page is stored! I am sure it's cache issue because if I querry page with no-cache headers it shows right page! I even tried changing which page is supposed to be main, but it still shows the old one. Support from Blue Host didn't help me either. Could you please tell me what is causing this?

**Comment by rowdya22** [comment]
The cache of stored in the wp-content/endurance-page-cache/ folder. When this folder is deleted the cache is essentially cleared. If this solution didn't work for you, check if your account has varnish caching and consider disabling it to test. 
The endurance-page-cache plugin is usually partnered with the endurance-browser-cache, because of this also be certain to clear your cache and cookies.

**Comment by BlindDespair** [comment]
I disabled has varnish caching as well at the very beginning too. This is not browser cache for sure, because if I open it in another browser or even on another device in another version it opens cached version. Also I checked what GET request and response headers page has, it says last modfied 11 February. Also it had status 304 Not modified. However request with no-cache headers returned status 200 Ok. I am out of ideas what makes this cached page and where it comes from.

**Comment by lukecav** [comment]
@BlindDespair
![endurance page cache](https://cloud.githubusercontent.com/assets/5797332/23681832/d7a00a44-034d-11e7-8ee7-7e2b8ade7061.png)

You can purge the cache from Plugins > Must-Use.

**Comment by sapila** [comment]
where do i find this option ? how else do i disable this ?

**Comment by lukecav** [comment]
@sapila 

Got to Plugins > Must-Use.

**Comment by sapila** [comment]
Yeah but ...where do i found the plugins option ? I cant seem to find it .... 
![desktop](https://cloud.githubusercontent.com/assets/6667204/24320787/99db32c2-113c-11e7-8a44-3a92a9e6dbd0.jpg)

**Comment by lukecav** [comment]
@sapila 

It would be in WordPress Admin under Plugins on your site.

https://codex.wordpress.org/Managing_Plugins

**Comment by sapila** [comment]
cool thnx ... i just chatted with someone from the support and he disabled the plugin.., thnx @lukecav
