### ISSUE TITLE
My website isn't refreshing

### ISSUE THREAD

**Issue by tvdir** [bluehost/endurance-page-cache#18]
Hi,
It looks like I'm having this issue on my Wordpress-hosted website. My homepage isn't refreshing. It stays on the previous homepage and is not updating when new content are posted. I don't understand why this plug-in is in my Wordpress site or why Bluehost has included this. I have been on two Bluehost chat lines for several hours trying to get this issue resolved, but so far no luck. Somebody please help.

**Comment by MikeHansenMe** [comment]
Hey tvdir, can you give me your domain? I can look into why your home is not refreshing.

**Comment by tvdir** [comment]
Thank you. SidewalksTV.com

Right now, it's still on a previous homepage without my updates. Every browser is showing different versions of info.

**Comment by tvdir** [comment]
I have noticed you have worked on the plugin since my request. Thank you for looking into this. I really wish I could have the plugin disable. The new changes do appear (finally), but only if you refresh a couple of times. When a repeat visitor comes to our site,  they will most likely see the old cached version. So, unless they press home a couple of times, they will think nothing has been updated. No new content.  Plus, I have been having issues creating pages and previewing my pages. Not 100% sure if this plugin is causing the problem, but I had no issues previously.

**Comment by tvdir** [comment]
My website isn't updating again. Please, please, please dissble this plugin. This isn't working. i have been patient. I have more new content this weekend. Thanks very much.

**Comment by MikeHansenMe** [comment]
Hey tvdir, I had changed the cache level to 0 for you. I just changed it to 1 to see if that will work better for you. 1 is asset only caching which means html will not cache and only css, js and images will. Please let me know if you continue to have trouble.

**Comment by tvdir** [comment]
Thank you, but it is still not working. My saved page is still on the previous info. I have been refreshing/reloading. I tried shift+reload and then the new info is there, but when i go back to the page it has returned to the old info. Also, my home page has random posts to display (popular interviews at the bottom of the page) and that is not changing either. I keep hitting refresh and that section stay the same. This is simply not working. Please consider disabling. I'm trying here.

**Comment by MikeHansenMe** [comment]
Page caching on the server is turned off. It looks like it may be your CDN caching things now.

**Comment by thetwosents** [comment]
Having same issue for mobile devices now. I have disabled the plugin and also can show it working in some browsers but not others. Considering this comes stock with Bluehost, I'd love a "If this happens to you, please do this" to offset the effects of the plugin. Love the functionality but yea, need to be able to see my changes pretty bad.

**Comment by MikeHansenMe** [comment]
Hey @thetwosents we are working on some documentation for this plugin but for the time being, if you give me your domain I will make sure that all the layers are turned off. In the settings general page you can change the level to 0 or Off and it will turn off the nginx layer and expires headers. Then you can turn it back on when you are ready.

**Comment by 3dassets** [comment]
I deleted my files and the website still feed me outdated content, how can this happen?

**Comment by earnjam** [comment]
If you don't want to have this caching enabled, you can change it in the WordPress admin under Bluehost > Performance (if you have the Bluehost plugin active), or under Settings in the Endurance Cache section by choosing Off (Level 0) from the select input.

Once disabled, you can remove the mu-plugin, or just leave it, as it does nothing at that point.

If you are still having problems, please feel free to add a comment with the domain of the site that is having trouble and I'll take a look, or you can open a new issue. We're working on some major improvements to the plugin and we'd love to get any issues resolved.

**Comment by sokel123** [comment]
Hi I have just subscribed with Bluehost and it seems Bluehost is having issues. I am currently testing phpMyAdmin by creating php pages that do not refresh even when new data are added to the database but it does not work. It caching and staying on old info. I have also noticed that this issue has been reported as far 2017 and worried that I am on a sinking ship

**Comment by earnjam** [comment]
@sokel123 Add this to your `.htaccess` file and it will disable caching. 
```
<ifModule mod_headers.c>
Header set X-Endurance-Cache-Level "0"
</ifModule>
```

**Comment by MikeHansenMe** [comment]
Hi @sokel123 in addition to what @earnjam mentioned. You may also need to log into your bluehost control panel and disable Cloudflare CDN on your account.
