### ISSUE TITLE
Minification Breaking LayersWP sites.

### ISSUE THREAD

**Issue by marcperel** [bluehost/endurance-page-cache#2]
Hey Guys,

Great work on the EPC, we have an issue however, some sites using the EPC and Layers are having an issue where their sliders are breaking, no doubt this is related to the minification.

The minification script is not clearing single line comments `//`, for example this script is kept in the minified script and essentially comments out the rest of the code:

```// Anchors```

It can be seen in the source here:
http://www.hummingbirdcrackers.com/about/

**Comment by MikeHansenMe** [comment]
Thanks for reporting this issue @marcperel. https://github.com/bluehost/endurance-page-cache/commit/9e090cb03ac352af7c5e62792d894800a09de115 should fix the problem.

**Comment by marcperel** [comment]
Baller, thanks @MikeHansenMe
