### ISSUE TITLE
Cache Issues with Safari / Explorer

### ISSUE THREAD

**Issue by amriemytakeontv** [bluehost/endurance-page-cache#21]
Hello - recently added endurance caches have screwed up my site - tried disabling / moving them out of the mu-plugin folder, but now, only if I'm logged in and on Chrome/Firefox, sometimes Safari, can I see updates/posts posted today.   Domain is mytakeontv.com.  I believe I'm currently set at 0, with everything enabled.  Might be something with my .htaccess?  Please help???

**Comment by MikeHansenMe** [comment]
I will take a look and get you taken care of.

**Comment by amriemytakeontv** [comment]
I'm working on a back up, so don't know if we need to wait that out?  Just let me know! 
Thanks!

**Comment by MikeHansenMe** [comment]
So I just looked at the account. This one did not get the cache plugin during install or through an interface. It has some other things going on. That explains why setting a level of 0 is not effecting it.  Can you send me an email at mike.hansen [a] endurance.com?
