### ISSUE TITLE
Endurance cache breaking when a user comments

### ISSUE THREAD

**Issue by acjmckay93** [bluehost/endurance-page-cache#24]
Hi 

I hope you can help, 
details
I recently started on Bluehost, and am having problems.

I installed a plugin that handles an event page, where users can view an event and comment on the event.
the only issue being when i tested it an left a comment the following errors came up.

Warning: Missing argument 2 for Endurance_Page_Cache::comment(), called in /home1/dynaerob/public_html/wp-includes/class-wp-hook.php on line 300 and defined in /home1/dynaerob/public_html/wp-content/mu-plugins/endurance-page-cache.php on line 167

Warning: Cannot modify header information - headers already sent by (output started at /home1/dynaerob/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/dynaerob/public_html/wp-content/plugins/jetpack/modules/subscriptions.php on line 722

Warning: Cannot modify header information - headers already sent by (output started at /home1/dynaerob/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/dynaerob/public_html/wp-content/plugins/jetpack/modules/subscriptions.php on line 728

Warning: Cannot modify header information - headers already sent by (output started at /home1/dynaerob/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/dynaerob/public_html/wp-includes/pluggable.php on line 1210

I can read a bit of code but am far from a boffin, maybe you can shed some light here

**Comment by acjmckay93** [comment]
the way i see it is i need to add an argument in the class-wp-hook.php , but before i go and break everything id like to get some advice

**Comment by MikeHansenMe** [comment]
hey @acjmckay93 thanks for letting me know about this. I just committed a fix and will get it into the next release. 
https://github.com/bluehost/endurance-page-cache/commit/fefa98c4ddd41cc860967b3197f139950c797bd0

**Comment by csonnek** [comment]
@MikeHansenMe I'm from Jetpack support and we're seeing this error in the wild again: 

```
Warning: Missing argument 2 for Endurance_Page_Cache::comment(), called in /home1/theroln5/public_html/wp-includes/class-wp-hook.php on line 300 and defined in /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php on line 167

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-content/plugins/jetpack/modules/subscriptions.php on line 722

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-content/plugins/jetpack/modules/subscriptions.php on line 728

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-includes/comment.php on line 531

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-includes/comment.php on line 532

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-includes/comment.php on line 533

Warning: Cannot modify header information - headers already sent by (output started at /home1/theroln5/public_html/wp-content/mu-plugins/endurance-page-cache.php:167) in /home1/theroln5/public_html/wp-includes/pluggable.php on line 1210
```

I've directed the customer to contact Bluehost support, but am noting the error in case anything changed. (reference for me 606942-zen )
