### ISSUE TITLE
No WP role-capability controls?

### ISSUE THREAD

**Issue by tmz1970** [bluehost/endurance-page-cache#25]
I created a custom Role with NO capabilities, except viewing entries from Gravity Forms. I even removed Read, and Level_0. Yet this role can still access the Cache dropdown in the top-bar of the wp-admin. Shouldn't this plugin respect wp role capabilities?

**Comment by MikeHansenMe** [comment]
@tmz1970 thanks for letting me know. I will get this fixed ASAP. We will be releasing a new version this week and will be sure to get this fix in.

**Comment by MikeHansenMe** [comment]
https://github.com/bluehost/endurance-page-cache/commit/e4d3d71a723e8fb2d50e8a1649391516e8c83ab0

That should resolve the role issue. Please let me know if you run into any additional issues, I am happy to get them resolved.
