### ISSUE TITLE
Page cache fails silently when term_id is zero (0); breaking site functionality

### ISSUE THREAD

**Issue by rsg-ndilworth** [bluehost/endurance-page-cache#26]
Endurance page cache fails silently when the function _edit_terms()_ (at line 200) gets a _term_id_ of zero (0). This causes scripts to fail, and silently undermines plugin functionality. Please add a check or other correction for this issue.

**Comment by MikeHansenMe** [comment]
@rsg-ndilworth thanks for reporting the issue. I will get a fix in for the next release. Which should go out sometime this week.

**Comment by MikeHansenMe** [comment]
https://github.com/bluehost/endurance-page-cache/commit/26bf5383940b0ba2fcab6a67f052b081f842ab8b

**Comment by rsg-ndilworth** [comment]
@MikeHansenMe. I have applied and tested your fix on my instance. It fixes my use case. Thank you.

**Comment by MikeHansenMe** [comment]
No problem. Thanks again for reporting it.
