### ISSUE TITLE
Need a way to force flushing the page cache

### ISSUE THREAD

**Issue by lvl99** [bluehost/endurance-page-cache#3]
I am currently trying to help a friend debug an issue with her site. Seems the page cache has cached her homepage (which had WP Maintenance Mode plugin showing a countdown) and now her homepage is stuck on the countdown, even though she has disabled the WP Maintenance Mode plugin.

If there was a way to flush the page cache through the plugin (or through a query var, à la W3 Total Cache) then that'd save us a lot of headaches.

Also, consider flushing the homepage/frontpage page when plugins are activated/deactivated.

**Comment by georgejipa** [comment]
Hello @lvl99,

You can empty the cache... by deleting the cached files from /wp-content/endurance-page-cache/ folder. In a future release of WPMM, I will try to delete/refresh the cache (generated by endurance-page-cache
) when the maintenance mode is activated/de-activated.

Thanks,
WP Maintenance Mode Dev

**Comment by MikeHansenMe** [comment]
This should be fixed by the PR georgejipa submitted.

https://github.com/bluehost/endurance-page-cache/pull/6

Thanks @lvl99 for reporting.

Thanks @georgejipa for the PR.

**Comment by MikeHansenMe** [comment]
Closing because the PR merged 11 days ago.
