### ISSUE TITLE
Pages won't refresh

### ISSUE THREAD

**Issue by Haussamen** [bluehost/endurance-page-cache#30]
I installed W3 Total Cache this week to improve my site's performance, and ever since I did that pages on my news website at http://nmpolitics.net/index don't update on all browsers and devices when I make changes. I've gone through tutorials to ensure I installed W3 Total Cache and gotten the advice that it's set up correctly, and the likely culprit is that Endurance Page Cache and Endurance Browser Cache are causing a conflict with W3 Total Cache. I've disabled Endurance Page Cache but have no option to disable Endurance Browser Cache. Can you help me?

**Comment by MikeHansenMe** [comment]
The Endurance Cache plugins will step aside if any other cache plugin gets installed. Like Super Cache, W3TC, or WP Rocket. With any additional caching plugins, the EPC basically steps aside and does nothing, allowing the other plugin to handle caching.

**Comment by Haussamen** [comment]
Thanks for getting back to me. So there's no way it could be causing problems? Does it leave residual code behind that could create a conflict?
