### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by TimothyAlex1** [bluehost/endurance-page-cache#31]
A couple of weeks ago, one of my WordPress plugins stopped working. I have been going back and forth with the developer since, and they pinpointed this error as the problem.:

PHP Fatal error:  Uncaught Error: Call to undefined function is_user_logged_in() in /.../wp-content/mu-plugins/endurance-page-cache.php:370
Stack trace:
#0 /.../wp-content/mu-plugins/endurance-page-cache.php(403): Endurance_Page_Cache->is_cachable()
#1 /.../wp-includes/class-wp-hook.php(286): Endurance_Page_Cache->finish('')
#2 /.../wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#3 /.../wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#4 /.../wp-includes/load.php(679): do_action('shutdown')
#5 [internal function]: shutdown_action_hook()
#6 {main}
  thrown in /.../wp-content/mu-plugins/endurance-page-cache.php on line 370

I pulled my error logs and also found this:

PHP Warning:  Cannot modify header information - headers already sent by (output started at /.../wp-admin/includes/template.php:2039) in /.../wp-content/mu-plugins/endurance-page-cache.php on line 498

When I disabled Endurance Page Cache, the plugin started working again. The Endurance Page Cache seems to have been added by JustHost, but is it necessary? I'm not sure exactly what it does since the caching still seems to be on.

**Comment by earnjam** [comment]
This is an older issue and should be resolved now. I'm going to close it, but if it still remains, please let feel free to reopen and let us know.
