### ISSUE TITLE
Http Error 500

### ISSUE THREAD

**Issue by rachelmsevey** [bluehost/endurance-page-cache#36]
I'm very much a beginner, so I hope on on the right path here. When I go to bluehost and try and login to my wordpress site, I get the following message:

This page isn’t working
box5454.temp.domains is currently unable to handle this request.
HTTP ERROR 500

I checked the error log in the file manager and the last few lines are:
     Stack trace:
     #0 /home1/sherryd0/public_html/wp-content/mu-plugins/endurance-page-cache.php(403): 
     Endurance_Page_Cache->is_cachable()
     #1 /home1/sherryd0/public_html/wp-includes/class-wp-hook.php(286): Endurance_Page_Cache-
     >finish('')
     #2 /home1/sherryd0/public_html/wp-includes/class-wp-hook.php(310): WP_Hook-
     >apply_filters(NULL, Array)
     #3 /home1/sherryd0/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
     #4 /home1/sherryd0/public_html/wp-includes/load.php(679): do_action('shutdown')
     #5 [internal function]: shutdown_action_hook()
     #6 {main}
       thrown in /home1/sherryd0/public_html/wp-content/mu-plugins/endurance-page-cache.php on 
       line 370

Am I correct in assuming the Endurance plugin is the issue here? Is there a way to fix it/disable it?

**Comment by MikeHansenMe** [comment]
hey @rachelmsevey I am going to jump in and take a look at the account. Do you mind sending me an email at mike.hansen @ endurance.com so I can share the details of what I find?

**Comment by rachelmsevey** [comment]
Thanks, @MikeHansenMe for your help!
