### ISSUE TITLE
Add <ifModule mod_headers.c> when modifying .htaccess

### ISSUE THREAD

**Issue by juliolopez78** [bluehost/endurance-page-cache#41]
Working on a local dev environment set up with [Vagrant](http://vccw.cc/) and I don't have `mod_headers.c` installed so the plugin's updates to the .htaccess file break my environment, then I have to go in and manually edit the .htaccess file.

I know this plugin was built for bluehost, but some of us devs like to have our dev environment local and only push stuff to prod after it's been tested.

I also know that I could just enable the headers mod on Apache ;)

However, it is convention to wrap rewrite rules with `<ifModule>`, so why not other directives?

Just change line [417](https://github.com/bluehost/endurance-page-cache/blob/master/endurance-page-cache.php#L417) to look like:

```php
$additions = "<ifModule mod_headers.c>\n" . 'Header set X-Endurance-Cache-Level "' . $this->cache_level . '"' . "\n</ifModule>\n";
```

**Comment by MikeHansenMe** [comment]
Thanks again @juliolopez78. Gonna close this one out.
