### ISSUE TITLE
This plugin can cause 404 errors when saving a menu in WordPress

### ISSUE THREAD

**Issue by Pikamander2** [bluehost/endurance-page-cache#59]
Whenever we saved our WordPress menu, this plugin was throwing an internal 404 error for every single menu item. As a result, the requests were taking far longer than they were supposed to and eventually started to time out completely (after 2 minutes) once the menu got big enough.

None of Bluehost's support agents seemed to know what the issue was, so I had to track down the issue using the [Query Monitor](https://wordpress.org/plugins/query-monitor/) plugin, which revealed this file as the source.

![image](https://user-images.githubusercontent.com/5246872/56270726-d2eb4000-60c4-11e9-9b01-3d3e5fbc1c40.png)

**Comment by wpscholar** [comment]
Thanks for the report @Pikamander2 ! We've got a fix in the queue for this.
