### ISSUE TITLE
Cache purge request making thousands of requests

### ISSUE THREAD

**Issue by micahwood** [bluehost/endurance-page-cache#66]
Not sure what triggered this as the UI said the cache setting was 0 (disabled) but I just found out this plugin was making multiple requests every second to my site for the past month. My access logs were filled with this:
```
107.180.40.150 - - [29/Apr/2019:11:55:29 -0700] "PURGE /.* HTTP/1.1" 301 - "http://MYDOMAIN.com/.*" "WordPress/4.9.10; https://MYDOMAIN.com; EPC/v1.5/option_update_fw_theme_google_fonts_list"
```

**Comment by wpscholar** [comment]
Oh, wow! It looks like we have the same name.

We've been doing a deep dive into the Endurance Page Cache lately and have identified a few issues which may be contributing to this. In one scenario, we found that changing the cache setting from certain locations had no effect. We have a fix ready to go for that and should be out within the next 7 days or so. It is possible that this is something you are running into.

As a workaround, try going to the general settings page in WordPress and changing the cache level to a higher level, saving, then knocking it back down to 0 and saving again. This should properly turn off caching and you _should_ stop seeing those items appear in your access logs. If it does not, let us know and we can look into it more.

**Comment by micahwood** [comment]
Thanks, found the database had a setting of 2 while the UI showed 0. Got it updated to 0 in the db as well and the requests stopped.
