### ISSUE TITLE
Endurance-Page-Cache Creating Thousands of Unwanted Directories?

### ISSUE THREAD

**Issue by DabidK** [bluehost/endurance-page-cache#8]
I happened to log into my Bluehost account today and noticed that I got a File Count error telling me “Your account contains more than 9740 directories and may pose a potential performance risk to the server.<br>Please reduce the number of directories for your account to prevent possible account deactivation.”

I was really surprised to see this, as I was nowhere **_near_** that number of directories a month or so ago the last time I checked. I went into my File Manager and discovered that I had THOUSANDS of new directories created that are all either totally empty or have 1 file in them and that are all along the lines of:

”
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/25/halo-micro-ops-series-1-falcon-high-ground-bunker-official-photos
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/24/halo-micro-ops-series-1-smalled-carded-sets-official-photos-2012
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/24/halo-micro-ops-series-1-high-ground-gate-mcfarlane-official-photos/embed
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/24/halo-micro-ops-series-1-high-ground-gate-mcfarlane-official-photos
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/22/halo-mega-bloks-warthog-resistance-set-fully-revealed
1 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2012/06/19/tons-halo-mega-bloks-news-facebook-qa
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/category
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/08/27
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/08
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/07/17
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/07/06
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/07/05
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/07/02
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/07
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/24
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/23
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/16
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/12
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/11
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/10
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/09
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/06/08
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/04/29
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/04/03
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/03/22
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/03/17
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/03/11
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/02/15
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/02/12
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/01/20
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/01/16
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016/01/14
0 : /home1/toyrevie/public_html/halotoynews/wp-content/endurance-page-cache/2016″

Upon studying the File Manager more, I can see that whatever this Endurance-Page-Cache thing is, it has basically created a whole new directory for every single post, category, page, tag AND photo that I’ve ever uploaded to one of my domains. So I can see WHY I have over 12,000 directories now, but I have no idea why it’s happening or how to stop it/fix it.

These example directories are all from halotoynews.com, but this problem is recurring across several of my other domains as well and I have no idea why. I don’t even have a caching plugin! I’ve never seen this Endurance-Page-Cache thing before and I have no idea what to do with it or how to delete these weird directories. 

My site was having issues with traffic around Thanksgiving and I upgraded to BlueHost Business Cloud Pro shortly thereafter, so all I can guess is that someone at BlueHost installed something since around Thanksgiving that's created this problem. I went into Wordpress Tools in my cPanel, but there's no "Endurance-Page-Cache" plugin that even exists there, as far as I can tell.

Regardless, I need to know what can be done to get this plugin (or whatever it is) off my sites before going over the directory limit becomes an issue. Can anyone help me?

**Comment by MikeHansenMe** [comment]
I will look into it and get it removed for you. We automatically add it
when your site receives the spike in traffic in an attempt to prevent the
site from crashing.

**Comment by DabidK** [comment]
Wow, thank you for the incredibly fast reply, Mike! I really appreciate it!

My primary domain is toyreviewdaily.com. Do you need the names of my sub-domains as well?

Thanks so much for being so helpful so quickly!!

**Comment by MikeHansenMe** [comment]
Hey @DabidK just wanted to follow up a bit. We did get this taken care (removed) of for you yesterday but I just wanted to relay a bit of info back to you. It looked like you had version 0.1 installed on your site. We have made a lot of improvements since that version. We have seen some large performance gains out of using this plugin and in the future plan on expanding it to help optimize some of our other caching layers. You can always turn this plugin on in the performance setting inside the MOJO Marketplace plugin if you want to try it again later.
